/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package filosofos;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import javax.swing.JFrame;
import javax.swing.JPanel;
/**
 *
 * @author gonzc
 */
public class Panel extends JPanel {
    Dimension dimension = new Dimension(440,440);
    JFrame base;
    /**
     * Creates new form Panel
     */
    public Panel() {
        this.setSize(dimension);
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void paintComponent(Graphics g){
        Graphics2D c =(Graphics2D) g;
        Color colorBorde = new Color(10,10,10);
        Color colorInterior = new Color(255,255,255);
        Ellipse2D borde = new Ellipse2D.Double(0, 0 , 440, 440);
        Ellipse2D interior = new Ellipse2D.Double(10, 10 , 420, 420);
        c.setColor(colorBorde);
        c.fill(borde);
        c.setColor(colorInterior);
        c.fill(interior);
    }
    public void Base(JFrame frameBase) {
        this.base = frameBase;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
